Feat 20 register docker
AllenNeuralDynamics/aind-metadata-service pull request #23
Opened 2022-11-23 23:55 UTC by jtyoung84

Closes #20
Closes #21

- Tested on a forked repo: https://github.com/jtyoung84/aind-metadata-service
- Updates issue template
- Updates unit test to handle change in aind-data-schema repo

2022-11-23 23:58 UTC, jtyoung84 commented
A few people requested to be tagged to review this pr. @aricAI I'll merge it once you approve it.

2022-11-30 17:57 UTC, aricAI requested changes
in publish.yml lines 17 and 33, set-output is deprecated. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

echo "version=$new_tag" >> $GITHUB_OUTPUT

2022-11-30 19:10 UTC, jtyoung84 commented
@dyf Should the owner by alleninstitute or allenneuraldynamics? The last two lines of the publish.yml file.

2022-11-30 19:41 UTC, camilolaiton approved these changes

2022-12-01 01:19 UTC, dyf approved these changes

2022-12-01 17:04 UTC, aricAI approved these changes

2022-12-01 17:21 UTC, merged